name: Build with ncc 

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build with ncc
      run: npx @vercel/ncc build index.js -o dist

    - name: Create new branch and commit changes
      id: create_branch
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Action"
        BRANCH_NAME=automated-build-$(date +'%Y%m%d%H%M%S')
        git checkout -b $BRANCH_NAME
        git add dist/index.js
        git commit -m "Automated build"
        git push origin $BRANCH_NAME
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        title: Automated build
        body: This is an automated build.
        branch: ${{ env.BRANCH_NAME }}